version: '2'
networks:
  default:
    external:
      name: aaa
services:
    redis-slave1:
          container_name: "redis-slave1"
          build: ./redis
          volumes:
              - ./conf/redis-slave1.conf:/usr/local/etc/redis/redis.conf
              - ./redis-slave1-data:/data
          networks:
           default:
             ipv4_address: 10.0.0.51
             aliases:
              - redis-slave1
          restart: always
    redis-slave2:
          container_name: "redis-slave2"
          build: ./redis
          volumes:
              - ./conf/redis-slave2.conf:/usr/local/etc/redis/redis.conf
              - ./redis-slave2-data:/data
          networks:
           default:
             ipv4_address: 10.0.0.52
             aliases:
              - redis-slave2
          restart: always
    redis-sentinel:
          container_name: "redis-sentinel"
          build: ./sentinel
          volumes:
              - ./conf/redis-sentinel.conf:/usr/local/etc/redis/sentinel.conf
              - ./redis-sentinel-data:/data
          networks:
           default:
             ipv4_address: 10.0.0.61
             aliases:
              - redis-sentinel
          restart: always
    redis-sentinel1:
          container_name: "redis-sentinel1"
          build: ./sentinel
          volumes:
              - ./conf/redis-sentinel1.conf:/usr/local/etc/redis/sentinel.conf
              - ./redis-sentinel1-data:/data
          networks:
           default:
             ipv4_address: 10.0.0.62
             aliases:
              - redis-sentinel1
          restart: always
