version: '2'
networks:
  default:
    external:
      name: testwifi
services:
    redis:
          container_name: "redis"
          image: redis
          volumes:
              - ./master-data:/data
          ports:
              - "6379:6379"
          restart: always
